### ISSUE TITLE
[Bug] Create Game from Game Gallery Client-side Errors

### ISSUE THREAD

**Issue by xHayden** [GTBitsOfGood/jennifer-anns-group#213] opened 2024-11-07 18:06 UTC
## Context
Clicking create game from the game gallery results in a client-side error. Refreshing fixes this.
Figure out what is causing the error and what can be done to stop it.

### Frontend
- Investigate client-side error
- Fix any client-side issues with create game

### Backend
- Fix any backend issues with create game

## Acceptance Criteria
- [ ] Investigate client-side error
- [ ] Fix frontend issues
- [ ] Fix backend issues (if any)

## Notes

**Comment by 03hchen** [comment] 2024-11-08 16:44
I think this is fixed in the dev branch: https://github.com/GTBitsOfGood/jennifer-anns-group/blob/37e0986d5c546564a70461ad5f8ffb1553b0f8cd/src/components/GameScreen/GamePage.tsx#L201

In prod branch it looks like this which causes the error below: https://github.com/GTBitsOfGood/jennifer-anns-group/blob/61cf6eb9676ad1cce0a1c9812eaee0b87f73c146/src/components/GameScreen/GamePage.tsx#L201

<img width="646" alt="Screenshot 2024-11-08 at 11 24 44 AM" src="https://github.com/user-attachments/assets/81e1f4ed-71ac-48c7-b5c4-5ec57206ba0c">

This line is from the game page (preview mode) which is pre-fetched on the create game screen (which is why curData is null). [Pre-fetching only happens in production](https://nextjs.org/docs/app/api-reference/components/link#prefetch) and seems like it can be caused by `router.replace` and not just `Link` components? 

I think this issue can be closed by merging dev into production

**Comment by xHayden** [comment] 2024-11-16 02:15
We just went over this in dms, but confirming in case this isn't resolved, there are still problems on dev despite the errors being resolved. The create game automatically redirects back to home.

**Closed as completed** 2024-11-16 03:18 UTC
Labels: bug, fullstack
